### PR TITLE
 Bugfix: Illegal move was possible (discarding when on hint 8 tokens)

### PR DESCRIPTION
**Pull request by jordruss**

### CODE REVIEW

**Review by drtnf — CHANGES_REQUESTED** [review]
Thanks for that. Shouldn't it be if hints==8?

**Comment by jordruss** [comment]
Oh yes you're right, hints==8

Also the BasicAgent runs up against this every so often, I'll put in a new pull for a random hint move. It's up to you whether that should be included in the main branch though!

**Review by drtnf — APPROVED** [review]

**Review by drtnf — APPROVED** [review]
Thanks.

**Comment by jordruss** [comment]
No problem!

**Pull request merged**
